version: '2'
services:
  db:
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - '~/Docker/mariadb/config:/etc/mysql/conf.d'
      - '~/Docker/mariadb/datadir:/var/lib/mysql'
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: dbtest
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - 'db:db'
    ports:
      - '8081:80'
    environment:
      MYSQL_USER: root
