version: "3"
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
  pgadmin4:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=bnugraha00@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password